import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "@progress/kendo-theme-default/dist/all.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-between max-w-7xl mx-auto my-5">
          <Link className="text-2xl font-bold" href="/">
            RichText
          </Link>
          <nav>
            <ul className="flex">
              <li>
                <Link href="/lexical">Lexcial</Link>
              </li>
            </ul>
          </nav>
        </header>

        <main className="max-w-7xl mx-auto ">{children}</main>
      </body>
    </html>
  );
}
